[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]

# Anvil local for production deployment on server
[rpc_endpoints]
anvil_local = "http://127.0.0.1:8545"
polygon_amoy = "https://rpc-amoy.polygon.technology"
polygon_mainnet = "https://polygon-rpc.com"
